version: '3'

services:

  # Services

  couchdb:
    image: couchdb
    ports:
      - "5984:5984"

  api-server:
    build: ./containers/api-server
    links:
      - couchdb
    environment:
      - ENV=production
      - COUCHDB_URL=http://couchdb:5984
      - NODE_PORT=80

  reverse-proxy:
    image: ./containers/reverse-proxy
    ports:
      - "80:80"
    links:
      - api-server
    volumes:
      - ./containers/reverse-proxy/conf.d:/etc/nginx/conf.d
    restart: always
